name: Apply changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # strategy:
    #   matrix:
    #     organization: ['apple', 'banana', 'peach']
    #     env: ['staging', 'production']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Set env values
      #   run: cat envs/${{ matrix.env }}/.env.${{ matrix.organization }} > .env.production
      # - name: Load .env file
      #   uses: xom9ikk/dotenv@v1.0.2
      #   with:
      #     mode: production
      # - name: Build
      #   run: |
      #     mkdir dist
      #     echo '/intelligence/* ${{ env.INTELLIGENCE }}/:splat 200' >> dist/_redirects
      #     echo '/user-management/* ${{ env.USER_MANAGEMENT }}/:splat 200' >> dist/_redirects
      #     echo '/* /intelligence' >> dist/_redirects
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: sites:create --name="test-netlify-cli-ci"
        env:
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
